# Site settings
title: Christian Blank
email: mail@cblank.de
description: Check24 Vergleichsportal
baseurl: ""
url: "http://cblank.de"
twitter_username: _cblank
github_username: 1blankz7
facebook_username: cblank.de
ntb_username: blanker
google_username: "101834777255001548316"
analytics_id: "UA-25956210-3"

# Build settings
markdown: kramdown
