# Site settings
title: "Christian Blank"
description: > # this means to ignore newlines until "email:"
  I'm a researcher, founder, investor and former professional sportsman.

email: mail@cblank.de
#blog logo
logo: "/assets/images/cb.jpg"
icon: "/assets/images/favicon.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Christian Blank'
author: 'Christian Blank'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/_cblank
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
  - icon:	github
    url:	https://github.com/1blankz7
    desc:	Fork me on github
  - icon:	university
    url:  https://haw-hamburg.academia.edu/ChristianBlank
  - icon:	university
    url:  https://www.researchgate.net/profile/Christian_Blank
  - icon:	linkedin
    url:  https://www.linkedin.com/in/christian-blank-55b669195/
  - icon:	xing
    url: https://www.xing.com/profile/Christian_Blank28/cv
